name: CI
on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  rust:
    name: Test Rust server code
    strategy:
      matrix:
        rust:
          - stable
          - 1.49.0
        include:
          - rust: stable
            extra_components: rustfmt
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ matrix.rust }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install libavcodec-dev libavformat-dev libavutil-dev libswscale-dev pkgconf
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.rust }}
        override: true
        components: ${{ matrix.extra_components }}
    - name: Test
      run: cargo test --all-features
    - name: Check formatting
      if: matrix.rust == 'stable'
      run: cargo fmt -- --check
